### ISSUE TITLE
AttributeError when parameters are documented in the class docstring.

### ISSUE THREAD

**Issue by anntzer** [PyCQA/pydocstyle#434]
Running pydocstyle 5.0.0 on
```python
class Blah:
    """
    Blah.

    Parameters
    ----------
    x : int
    """

    def __init__(self, x):
        pass
```
results in
```
<elided>
  File ".../lib/python3.8/site-packages/pydocstyle/checker.py", line 1002, in get_function_args
    function_arg_node = ast.parse(textwrap.dedent(function_string)).body[0].args
AttributeError: 'ClassDef' object has no attribute 'args'
```

One can argue whether parameter lists should be allowed on the class docstring rather than the init docstring, but in any case this shouldn't fail with an AttributeError.

**Comment by jbloom** [comment]
Same problem for me. Code that was now passing linting fails.

**Comment by europ** [comment]
I had the same problem by using pydocstyle 5.0.0.

**Comment by alanverdugo** [comment]
I got the same problem here.

**Comment by Nurdok** [comment]
Thanks for reporting, and thanks for the reproducing example, it's really helpful! I'm working on a fix and will try to release 5.0.1 ASAP.

**Comment by Nurdok** [comment]
@anntzer @jbloom @europ @alanverdugo 

I released 5.0.1 with a bugfix, hopefully that should do it.
I would highly appreciate it if you can try the new version and report back. 

Thanks everyone!

**Comment by alanverdugo** [comment]
All good now @Nurdok ! It works fine with 5.0.1
Thanks for fixing this so quickly! :1st_place_medal:

**Comment by europ** [comment]
@Nurdok I can confirm that release 5.0.1 works :heavy_check_mark:
